"""Initial migration

Revision ID: b048cc7059e4
Revises:
Create Date: 2023-11-25 09:53:31.168288

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b048cc7059e4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cakes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("comment", sa.String(length=200), nullable=False),
        sa.Column("imageUrl", sa.String(), nullable=False),
        sa.Column("yumFactor", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cakes_id"), "cakes", ["id"], unique=False)
    op.create_index(op.f("ix_cakes_name"), "cakes", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cakes_name"), table_name="cakes")
    op.drop_index(op.f("ix_cakes_id"), table_name="cakes")
    op.drop_table("cakes")
    # ### end Alembic commands ###
