# Generated by Django 4.2.7 on 2023-11-24 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cake_server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cake",
            name="comment",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="cake",
            name="imageUrl",
            field=models.URLField(validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name="cake",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="cake",
            name="yumFactor",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
